# Generated by Django 4.0.1 on 2022-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0005_alter_profile_birth_date_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
