# Generated by Django 4.0.1 on 2022-01-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0007_alter_post_options_post_caption_post_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
